"use client";

import { motion, useReducedMotion } from "framer-motion";
import { ArrowUpRight, Mail, MapPin, Phone } from "lucide-react";
import Image from "next/image";

const reveal = { hidden: { opacity: 0, y: 20 }, visible: { opacity: 1, y: 0, transition: { duration: 0.6, ease: [0.22, 1, 0.36, 1] } } };

export default function Contact() {
  const reduced = useReducedMotion();
  const props = reduced ? {} : { initial: "hidden", whileInView: "visible", viewport: { once: true, amount: 0.18 } };
  return <section id="contact" aria-labelledby="contact-heading" className="relative overflow-hidden bg-[#030814] py-20 sm:py-24"><div className="relative mx-auto max-w-7xl px-6 sm:px-8 lg:px-10"><motion.div {...props} variants={reveal} className="border-y border-white/12 py-12 sm:py-16"><div className="grid gap-10 lg:grid-cols-12"><div className="lg:col-span-5"><span className="text-xs font-semibold tracking-[0.18em] text-[#f0cf85] uppercase">AJCE · Kottayam, Kerala</span><h2 id="contact-heading" className="mt-5 max-w-md text-3xl font-semibold leading-[1.06] tracking-[-0.04em] text-white sm:text-4xl">Ready to find your direction?</h2><a href="#top" className="group mt-8 inline-flex min-h-11 items-center gap-2 border-b border-[#dfb861]/70 text-sm font-semibold text-white transition-colors hover:text-[#f0cf85] focus-visible:outline-2 focus-visible:outline-offset-4 focus-visible:outline-[#f0cf85]">Back to top <ArrowUpRight size={16} aria-hidden="true" className="transition-transform group-hover:-translate-y-0.5 group-hover:translate-x-0.5" /></a></div><address className="grid gap-6 not-italic text-sm leading-6 text-white/65 sm:grid-cols-3 lg:col-span-7"><div><MapPin size={18} aria-hidden="true" className="mb-3 text-[#f0cf85]" />Amal Jyothi College of Engineering<br />Koovappally P.O., Kanjirappally<br />Kottayam, Kerala 686518</div><div><Mail size={18} aria-hidden="true" className="mb-3 text-[#f0cf85]" /><a className="transition-colors hover:text-[#f0cf85] focus-visible:outline-2 focus-visible:outline-offset-4 focus-visible:outline-[#f0cf85]" href="mailto:info@ajce.in">info@ajce.in</a><br /><a className="transition-colors hover:text-[#f0cf85] focus-visible:outline-2 focus-visible:outline-offset-4 focus-visible:outline-[#f0cf85]" href="mailto:info@amaljyothi.ac.in">info@amaljyothi.ac.in</a></div><div><Phone size={18} aria-hidden="true" className="mb-3 text-[#f0cf85]" /><a className="transition-colors hover:text-[#f0cf85] focus-visible:outline-2 focus-visible:outline-offset-4 focus-visible:outline-[#f0cf85]" href="tel:+919072661610">+91 90726 61610</a><br /><a className="transition-colors hover:text-[#f0cf85] focus-visible:outline-2 focus-visible:outline-offset-4 focus-visible:outline-[#f0cf85]" href="tel:+919496094661">+91 94960 94661</a></div></address></div></motion.div><div className="flex items-center gap-3 pt-7"><Image src="/images/ajce/logo/ajce-logo.jpg" alt="AJCE official emblem" width={36} height={36} className="size-9 rounded-full bg-white object-cover" /><p className="text-xs text-white/38">© {new Date().getFullYear()} Amal Jyothi College of Engineering. Content and contact details sourced from AJCE’s official website.</p></div></div></section>;
}
