"use client";

import { motion, useReducedMotion } from "framer-motion";
import { ArrowUpRight, BriefcaseBusiness, UsersRound } from "lucide-react";

const reveal = { hidden: { opacity: 0, y: 24 }, visible: { opacity: 1, y: 0, transition: { duration: 0.62, ease: [0.22, 1, 0.36, 1] } } };

export default function Placements() {
  const reduced = useReducedMotion();
  const props = reduced ? {} : { initial: "hidden", whileInView: "visible", viewport: { once: true, amount: 0.18 } };
  return <section id="placements" aria-labelledby="placements-heading" className="relative overflow-hidden bg-[#030814] py-24 sm:py-32 lg:py-40"><div aria-hidden="true" className="absolute inset-x-0 top-0 h-px bg-white/10" /><div className="relative mx-auto max-w-7xl px-6 sm:px-8 lg:px-10"><motion.div {...props} variants={reveal} className="grid gap-10 border border-white/12 p-7 sm:p-10 lg:grid-cols-12 lg:items-end lg:p-14"><div className="lg:col-span-7"><div className="mb-7 flex items-center gap-3"><span className="h-px w-9 bg-[#dfb861]" /><span className="text-xs font-semibold tracking-[0.18em] text-[#f0cf85] uppercase">Placements & Careers</span></div><h2 id="placements-heading" className="max-w-3xl text-balance text-4xl font-semibold leading-[1.02] tracking-[-0.045em] text-white sm:text-5xl">Build readiness for the work ahead.</h2><p className="mt-7 max-w-xl text-base leading-7 text-white/68">AJCE states that placement support is coordinated through a central office and departmental cells, with training and opportunities designed to help students prepare for professional life.</p></div><div className="lg:col-span-4 lg:col-start-9"><div className="border-l border-[#dfb861] pl-6"><p className="text-5xl font-semibold tracking-[-0.06em] text-white">₹20 LPA</p><p className="mt-3 text-sm leading-6 text-white/62">Highest package stated by AJCE. Outcomes vary by programme and graduating year.</p></div><a href="#apply" className="group mt-9 inline-flex min-h-11 items-center gap-2 border-b border-[#dfb861]/70 text-sm font-semibold text-white transition-colors hover:text-[#f0cf85] focus-visible:outline-2 focus-visible:outline-offset-4 focus-visible:outline-[#f0cf85]">Talk to admissions <ArrowUpRight size={16} aria-hidden="true" className="transition-transform group-hover:-translate-y-0.5 group-hover:translate-x-0.5" /></a></div></motion.div><motion.div {...props} variants={reveal} className="mt-6 grid gap-5 sm:grid-cols-2"><div className="border border-white/12 p-7"><BriefcaseBusiness size={21} aria-hidden="true" className="text-[#f0cf85]" /><h3 className="mt-8 text-xl font-semibold text-white">Career preparation</h3><p className="mt-3 text-sm leading-6 text-white/61">Training, guidance, and encounters with professional expectations are part of the journey.</p></div><div className="border border-white/12 p-7"><UsersRound size={21} aria-hidden="true" className="text-[#f0cf85]" /><h3 className="mt-8 text-xl font-semibold text-white">Departmental support</h3><p className="mt-3 text-sm leading-6 text-white/61">AJCE describes a placement cell in each department alongside central coordination.</p></div></motion.div></div></section>;
}
